### ISSUE TITLE
Add documentation on how to use ddcutil without sudo

### ISSUE THREAD

**Issue by DonPavlov** [daitj/gnome-display-brightness-ddcutil#1]
Hi. I installed it on Ubuntu 19.10 but get an error on the extensions webpage.
The commands work great in cli while using sudo. Maybe also add into your description the requisits. Which package to install. Adding your user to i2c group.

Also love the extension, was already thinking about doing it myself, but stopped after not having enough time.

Great work.

**Comment by themightydeity** [comment]
Thanks for the suggestion. 

Basically the extension expects that ddcutil to work without root before  you install it, i.e. ddcutil needs rw access to /dev/i2c-* which can be done in multiple ways in different distros.

I will update readme later on when I have time, I am trying to make some quality of life changes to the extension as well. 

I did this addon just quickly for personal use, since the name includes ddcutil I was hoping for users to find out what it is on their own. 

I am leaving this issue open for the time being.

**Comment by evansan** [comment]
# Brightness Control
1. install `ddcutil`
2. Manually load kernel module `i2c-dev`
```
modprobe i2c-dev
```
3. Verify that your monitor supports brightness control
```
ddcutil capabilities | grep "Feature: 10"
```
4. udev rule for giving group i2c RW permission on the `/dev/i2c` devices
```
sudo cp /usr/share/ddcutil/data/45-ddcutils-i2c.rules /etc/udev/rules.d
```
5. Create i2c group and add yourself
  ```
  sudo usermod your-user-name -aG i2c
  sudo groupadd --system i2c
  ```
6. load `i2c-dev` automatically
```
touch /etc/modules-load.d/i2c.conf
echo "i2c-dev" >> /etc/modules-load.d/i2c.conf
```

**Comment by daitj** [comment]
@evansan Thank you, I have added this to readme
