### ISSUE TITLE
translation help needed

### ISSUE THREAD

**Issue by ViBE-HU** [daitj/gnome-display-brightness-ddcutil#118]
i'm actually trying to translate your plugin. but some details needed and i also have to discuss about some functions which are not so self-explanatory before i finish.

1. "Apply" string is not in the text file. i guess it is missing?

2. there are some ddcutil related strings. where are those show up? what is the context?

3. there are some custom shortcut related strings in the text file. i guess those are keyboard shortcut related too but not appearing on the GUI. are those future functions or already deprecated things?

4. what "Allow Zero Brightness" do?

5. what "Disable Display State Check" do?

**Comment by daitj** [comment]
Please do note that you have the latest version of the extension before going forward. 

@oscfdezdz can tell you about the "Apply" string and keyboard shortcut. He is the one who implemented Preferences UI.  

"Allow Zero Brightness" is to allow brightness slider to set value 0 instead of 1, setting 0 in some monitors caused them to be totally blank. 

"Disable Display State Check" is to disable check if the display is ON and that we can comminicate with display using DDC to get `D6` (power mode) vcp info.

Just make a PO file and push your changes, if something is missing we can add that later on.

**Comment by oscfdezdz** [comment]
> 1. "Apply" string is not in the text file. i guess it is missing?

"Apply" string was removed a few versions back (3941f9e8118287a60ad9be89b4cbbc62f4e04fe7), that's why is missing.

> 3\. there are some custom shortcut related strings in the text file. i guess those are keyboard shortcut related too but not appearing on the GUI. are those future functions or already deprecated things?

The strings related to the custom keyboard shortcuts that are shown in the GUI are: https://github.com/daitj/gnome-display-brightness-ddcutil/blob/d207ff286c99035ba693ee2ed79899ba345126bc/display-brightness-ddcutil%40themightydeity.github.com/po/display-brightness-ddcutil.pot#L60-L74 and https://github.com/daitj/gnome-display-brightness-ddcutil/blob/d207ff286c99035ba693ee2ed79899ba345126bc/display-brightness-ddcutil%40themightydeity.github.com/po/display-brightness-ddcutil.pot#L116-L131 if there are any other strings, they are not shown in the interface or handled by GTK translations directly.

**Comment by ViBE-HU** [comment]
Now I see. Thanks guys. I'm using version 31(?) cause i'm on Ubuntu 22.04 with Gnome 42.9.
