### ISSUE TITLE
Change brightness of all screens simultaneously

### ISSUE THREAD

**Issue by P1zz4br0etch3n** [daitj/gnome-display-brightness-ddcutil#12]
Would be nice if one could change all screens brightness with scrolling on the indicator icon.

**Comment by Benimautner** [comment]
If you are still interested, I added an extra slider for all displays in Pull request #15 
Not sure about the scroll wheel though.

**Comment by daitj** [comment]
If you want to use the feature already now, I have created a new [branch](https://github.com/daitj/gnome-display-brightness-ddcutil/tree/combined-slider) with the PR #15 

But I would like to add settings in the extension so that people can choose how they want it to be displayed. Also I suppose you should be able to lock the different levels for different monitors and use "All" slider accordingly.

**Comment by daitj** [comment]
added in #15
