### ISSUE TITLE
"Initializing" after some time

### ISSUE THREAD

**Issue by Razer0123** [daitj/gnome-display-brightness-ddcutil#18]
After some time it stops working and i have to restart Gnome to make it work again

Not sure which kind of info / files i could attach to help fix this

Any help would be appreciated, i love this extension

**Comment by daitj** [comment]
@Razer0123 

I have added a reload button in the extension and also fixed some issues. Unfortunately it will only work in gnome40. 

You could try it out and let me know what happens?

**Comment by Razer0123** [comment]
Yes but how should i update it?

I see no update on Gnome Extensions

**Comment by daitj** [comment]
I have submitted a versio, it needs to be reviewed by gnome folks and
then it will be published.

You can also clone this repo and copy `display-brightness-
***@***.***` directory  to `~/.local/share/gnome-
shell/extensions/`
and then complie settings schemas like this:

```
glib-compile-schemas ~/.local/share/gnome-shell/extensions/display-
***@***.***/schemas/

```

Restart the gnome shell and then you should be getting the new version
running.

**Comment by daitj** [comment]
I have submitted a versio, it needs to be reviewed by gnome folks and
then it will be published.

You can also clone this repo and copy `display-brightness-ddcutil@themightydeity.github.com` directory  to `~/.local/share/gnome-
shell/extensions/`
and then complie settings schemas like this:

```
glib-compile-schemas ~/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/schemas/
```
Restart the gnome shell and then you should be getting the new version
running.

**Comment by Razer0123** [comment]
Updated the extension, will check once the problem shows again to see if the reload work

Just an idea, could it be possible to add a setting to run the reload command once in X minutes? So i don't have to press the reload button manually

**Comment by Razer0123** [comment]
Ok i can report back with unfortunately bad news, it still shows initializing, but initializing only, there is no reload button (that is otherwise present)

**Comment by daitj** [comment]
@Razer0123 which system are you using? It feels like very peculiar problem?

The extension will show "Initializing" only when whole extension is reloaded, which  happens  in two cases, when monitor(s) layout changes or when gnome-shell crashes.

Could it be that some other extension is crashing the gnome-shell?

Do you have multiple monitors and you change the layout frequently, meaning if you disable one monitor and enable etc?

Could you share your gnome-shell log here?

`journalctl -b /usr/bin/gnome-shell`

**Comment by Razer0123** [comment]
Archlinux and Gnome 40

Here is the log
[log.txt](https://github.com/daitj/gnome-display-brightness-ddcutil/files/6346533/log.txt)

**Comment by daitj** [comment]
Thanks, I can see one error which could have been causing the problem. I have update my repo and will update to gnome extensions soon if this is the issue. You could check the fix out by:

Opening `~/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js` and then replacing line no 21 from:
`const {GLib, Gio, St} = imports.gi;`
to
`const {GLib, Gio, St, Gtk} = imports.gi;`

Then restart gnome-shell.

**Comment by Razer0123** [comment]
Done, let's see if this fixes it, thanks

Will report back soon

**Comment by Razer0123** [comment]
Happened again :(

**Comment by daitj** [comment]
I have a feeling that it is due to some other extension, I can see from the log that there are logs of panel changes happening.
Have you tried disabling everything else and just enabling this extension and checking it out. 

If you just want a fix for your use case then, I would suggest to add an extra line `addSettingsItem();` in the same file above.
below `addTextItemToPanel("Initializing");` in line no. 92.

**Comment by Razer0123** [comment]
No i have not tried but i will

What does the suggested edit do?

**Comment by daitj** [comment]
It would add settings and reload button.

**Comment by Razer0123** [comment]
Done, will report back

Can you point me exactly to which line do you think is causing the issues? with panel you are referring to the top bar i suppose

**Comment by leocomitale** [comment]
I fixed a similar problem (stuck on "initializing") on Fedora by giving my user id permission to access the /dev/i2c* files necessary for ddcutil to detect and control my monitor.  The ddcutil documentation details the steps necessary [here](https://www.ddcutil.com/i2c_permissions/).  Once I did that this extension works fine.

**Comment by daitj** [comment]
@Razer0123

"Initializing" should only be shown when extension is reloaded and before populating the displays(widgets) to the menu. 

So basically in this extension:

When Panel (position) changes are detected, it reloads the list of displays(widgets, not the extensions).
You can check this by searching `Panel change detected, reloading widgets` in the logs. This is what I think is happening mostly and since there was a `Gtk is not defined error`, which caused the extension to stay in failed state. But this shouldn't reload the whole extension, which is why I was thinking that there might be other extensions causing unecessarry panel changes. 


When monitor (layout) changes are detected, it reloads the whole extension. Reload button also reloads the whole extension.
I do not see any place where monitor change is happening, it seems like you have only one monitor. 


I still see `Gtk is not defined` in your last log though in line 11906. Have you done the changes mentioned in [this comment](https://github.com/daitj/gnome-display-brightness-ddcutil/issues/18#issuecomment-823619980)?
```
apr 20 22:34:14 archlinux gnome-shell[5244]: JS ERROR: ReferenceError: Gtk is not defined
                                             addSettingsItem@/home/alessandro/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:138:35
                                             reloadMenuWidgets@/home/alessandro/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:174:5
                                             parseDisplaysInfoAndAddToPanel/</</<@/home/alessandro/.local/share/gnome-shell/extensions/display-brightness-ddcutil@themightydeity.github.com/extension.js:229:50
                                             spawnWithCallback/<@/home/alessandro/.local/share/gnome-shell/extensions/display-brightness-d
``` 


Let me know what happens to you. May be I should remove panel changes events totally because with reload button it is not needed anymore. Monitor changes will stay as it is nice to just have monitor that are active in the list.

**Comment by Razer0123** [comment]
Yes i did the changes you mentioned

I've tried disabling a few extensions to see what happens, i might send another log in a few hours

But yes maybe removing panel changes could be a good idea, seems redundant

**Comment by Razer0123** [comment]
Happened again today, your latest change showed the reload and that fixed it, could you please push it on gnome extensions in the meantime that panel check gets removed?

**Comment by Razer0123** [comment]
Any news?

**Comment by daitj** [comment]
I have uploaded the new version, it should be live within a day or two. I have removed the panel signals, you could check that out and let me know if your issue is actually resolved?

I suppose the workaround to have the settings and reload button will be handy but it would be nice to get the probelm fixed.

**Comment by Razer0123** [comment]
Will do, thanks for your effort

**Comment by Razer0123** [comment]
Reportin back, never happened until today, when it happened but it fixed itself without me having to press the reload button
