### ISSUE TITLE
[Suggestion] Drop down brightness control

### ISSUE THREAD

**Issue by jacksongoode** [daitj/gnome-display-brightness-ddcutil#50]
I was imagining that one UI option that would conserve space and fit nicely with another similar plugin would be to hide the sliders within the brightness slider, much like [Sound Input & Output Device Chooser](https://github.com/kgshank/gse-sound-output-device-chooser).

![image](https://user-images.githubusercontent.com/54308792/150561960-0c73c347-7eee-437c-b66a-7ee3bc4ea22c.png)

**Comment by daitj** [comment]
I cannot think of how this would benefit, or may be I do not understand your suggestion? 

For a single monitor there is only one slider, so that just takes least amount of space already.

For multiple monitors you usually want to change multiple brightness at the same time, unlike for sound output which is just one. Multiple monitor could be under a sub menu when "all slider" is visible. 

Another preference could be that you could just have one "all slider" instead of having "all slider" and rest of the monitors.

**Comment by nfnvsc** [comment]
@daitj An option for **just** the 'all slider' would be a good addition. Most of the times I only use the All slider (with multiple monitors).

**Comment by daitj** [comment]
New version has this feature now. You can use only "All" slider while hiding other displays.
