### ISSUE TITLE
[suggestion] option for "overamplification"

### ISSUE THREAD

**Issue by MightyPrince1** [daitj/gnome-display-brightness-ddcutil#73]
At least on my display, the brightest that it can go is a value of 255 and not 100. I like the idea of using this extension, but I usually have it set to 255. Adding an option for the limit to be at 255 (and add in brackets something like experimental if you want to would make this extension a whole lot better in my eyes)

Love the work that you are doing btw

**Comment by daitj** [comment]
I also have a display with 255, the sliders you see are in percentage and is automatically translated into 0-255 value.  Only reason this won't work is if ddcutil is not reporting the value correctly.

You can check it using:

ddcutil getvcp D6 --bus <display_bus_id>

**Comment by MightyPrince1** [comment]
for me `ddcutil getvcp D6 --bus 10` yields `Bus /dev/i2c-10 not found`

**Comment by daitj** [comment]
You can get list of available buses using: 

ddcutil detect

**Comment by MightyPrince1** [comment]
now it reported` VCP code 0xd6 (Power mode                    ): DPM: On,  DPMS: Off (sl=0x01)`

**Comment by daitj** [comment]
Sorry my bad, vcp code should 10 instead D6, you need to check with:

ddcutil getvcp 10 --bus your_bus

**Comment by MightyPrince1** [comment]
it reports 100, but I know that the maximum is 255
`VCP code 0x10 (Brightness                    ): current value =   255, max value =   100`

could you add an option to ignore `ddcutil getvcp 10 --bus 4`

**Comment by daitj** [comment]
Could you put your monitor model here, if someone else also runs into same issue, it would be good to have it. 

Have you checked in ddcutil's repo, if they have some workaround for this sort of use cases. Ideally it would be better to have the fix there.

**Comment by MightyPrince1** [comment]
Samsung Odyssey G5 LC27G55TQWEXXT 27" VA CURVED 2K 144Hz

**Comment by daitj** [comment]
As I can see it [here](https://github.com/rockowitz/ddcutil/issues/200#issuecomment-816279026), there is nothing ddcutil folks can do about this, it is a bad implementation of DDC/CI from Samsung, since your monitor is not reporting stuff correctly, it is a very unique issue. 

## Solution 1
I suggest you to create a wrapper script for ddcutil in your `$HOME/.local/bin/ddcutil` then add that to your `PATH` if it is not there already.

This script will call for real `/usr/bin/ddcutil` and changes max value, when this extension calls for `ddcutil getvcp --brief 10 --bus 10`

example:
```
if [[ $string == *"getvcp --brief 10 --bus 10"* ]]; then
    /usr/bin/ddcutil "$@" | sed "s/100$/255/"
else
    /usr/bin/ddcutil "$@" 
fi
```


## Solution 2
 
You can clone (fork) this repo and fix the changes for you only. You need to replace `vcpInfosArray[4]` with `255` in following line:

https://github.com/daitj/gnome-display-brightness-ddcutil/blob/42adb44515e4de0294c5823b806c10a09c04f4d5/display-brightness-ddcutil%40themightydeity.github.com/extension.js#L330
