### ISSUE TITLE
[Feature request] Add a setting for sleep multiplier

### ISSUE THREAD

**Issue by Igetin** [daitj/gnome-display-brightness-ddcutil#74]
By default, ddcutil has a noticable lag when setting the brightness even when using `--bus`, which is the fastest display selection option. The [Performance and Tuning Options](https://www.ddcutil.com/performance_options/) section of the documentation describes the `--sleep-multiplier` option, which can be used to tune the default sleep period. The docs mention that “typically ddcutil spends approximately 90% of its elapsed time sleeping”. The optimal value for this varies from monitor to monitor, so it would be useful to be able to supply a custom sleep multiplier in the extension’s settings.

On my personal monitors I can use ddcutil with the setting `--sleep-multiplier .1` without problems, and the brightness change is almost instant (that is, I can’t notice the lag with my eyes compared to the default).

**Comment by daitj** [comment]
This is added in new version

**Comment by daitj** [comment]
According to the documentation multiplier 1 mean anything between 40ms-200ms, so that would make 0.1 = 4ms-20ms that is right now if the settings is 4ms, multiplier becoms 0.1 

The real reason why it is not instantenous for you may lie [here](https://github.com/daitj/gnome-display-brightness-ddcutil/blob/54f9b71b0c174e014de0ddd272cfde655ca4d200/display-brightness-ddcutil%40themightydeity.github.com/indicator.js#L232) 

Are you scrolling or using keyboard shortcut or directly clicking somewhere in the slider to change brightness ?

If you are scrolling then to prevent multiple requests, I have used 500ms delay, you can change that to something small and see what happens to you?

**Comment by daitj** [comment]
The ms thing was just so that I wanted to store it as integer instead of float. 

About the delay, main issue lies in how slider emits slider value updated event. The thing you experienced is why there is 500ms delay so that, no new ddcutil query is made if the slider value is updated within 500ms of the previous one, this is what happens when you drag or scroll above the slider. Was `40` the least you can have without issues?

If it waits for previous to complete before send a new one, for example if you drag from 0 to 20, it will be 20 query waiting in queue to complete, so 20 queries * 4ms, 80ms to change in total.

I will check how ddccontrol tackles this, may be get some inspiration from them.

**Comment by daitj** [comment]
Looking at the ddcontrol's constants comments
```
#define DELAY   		45000	/* uS to wait after write */
#define CONTROL_WRITE_DELAY   80000	/* uS to wait after writing to a control (default) */
```

They have write immediately and then cooldown (waiting=DELAY+CONTROL_WRITE_DELAY).
 
Whereas this extension is collecting (waiting) and then writing.

I will look into changing the logic that way, I already have some ideas in my mind, it should fix your problem. But sadly no ETA on this.
